/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/analytics/AnalyticsPage': RouteRecordInfo<'/analytics/AnalyticsPage', '/analytics/AnalyticsPage', Record<never, never>, Record<never, never>>,
    '/assets/AssetLibraryPage': RouteRecordInfo<'/assets/AssetLibraryPage', '/assets/AssetLibraryPage', Record<never, never>, Record<never, never>>,
    '/auth/ForgotPassword': RouteRecordInfo<'/auth/ForgotPassword', '/auth/ForgotPassword', Record<never, never>, Record<never, never>>,
    '/auth/Login': RouteRecordInfo<'/auth/Login', '/auth/Login', Record<never, never>, Record<never, never>>,
    '/auth/ResetPassword': RouteRecordInfo<'/auth/ResetPassword', '/auth/ResetPassword', Record<never, never>, Record<never, never>>,
    '/auth/Signup': RouteRecordInfo<'/auth/Signup', '/auth/Signup', Record<never, never>, Record<never, never>>,
    '/Contact': RouteRecordInfo<'/Contact', '/Contact', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Manual': RouteRecordInfo<'/Manual', '/Manual', Record<never, never>, Record<never, never>>,
    '/Privacy': RouteRecordInfo<'/Privacy', '/Privacy', Record<never, never>, Record<never, never>>,
    '/projects/ProjectWorkspacePage': RouteRecordInfo<'/projects/ProjectWorkspacePage', '/projects/ProjectWorkspacePage', Record<never, never>, Record<never, never>>,
    '/projects/workspace/AssetLivePreviewGrid': RouteRecordInfo<'/projects/workspace/AssetLivePreviewGrid', '/projects/workspace/AssetLivePreviewGrid', Record<never, never>, Record<never, never>>,
    '/projects/workspace/AssetTab': RouteRecordInfo<'/projects/workspace/AssetTab', '/projects/workspace/AssetTab', Record<never, never>, Record<never, never>>,
    '/projects/workspace/AudioTab': RouteRecordInfo<'/projects/workspace/AudioTab', '/projects/workspace/AudioTab', Record<never, never>, Record<never, never>>,
    '/projects/workspace/CaptionsTab': RouteRecordInfo<'/projects/workspace/CaptionsTab', '/projects/workspace/CaptionsTab', Record<never, never>, Record<never, never>>,
    '/projects/workspace/Chatbot': RouteRecordInfo<'/projects/workspace/Chatbot', '/projects/workspace/Chatbot', Record<never, never>, Record<never, never>>,
    '/projects/workspace/ChatContentRenderer': RouteRecordInfo<'/projects/workspace/ChatContentRenderer', '/projects/workspace/ChatContentRenderer', Record<never, never>, Record<never, never>>,
    '/projects/workspace/PipelineTab': RouteRecordInfo<'/projects/workspace/PipelineTab', '/projects/workspace/PipelineTab', Record<never, never>, Record<never, never>>,
    '/projects/workspace/ScriptTab': RouteRecordInfo<'/projects/workspace/ScriptTab', '/projects/workspace/ScriptTab', Record<never, never>, Record<never, never>>,
    '/projects/workspace/StoryboardTab': RouteRecordInfo<'/projects/workspace/StoryboardTab', '/projects/workspace/StoryboardTab', Record<never, never>, Record<never, never>>,
    '/projects/workspace/UserMessageRenderer': RouteRecordInfo<'/projects/workspace/UserMessageRenderer', '/projects/workspace/UserMessageRenderer', Record<never, never>, Record<never, never>>,
    '/projects/workspace/WorkspaceAddEpisodeModal': RouteRecordInfo<'/projects/workspace/WorkspaceAddEpisodeModal', '/projects/workspace/WorkspaceAddEpisodeModal', Record<never, never>, Record<never, never>>,
    '/projects/workspace/WorkspaceCanvasArea': RouteRecordInfo<'/projects/workspace/WorkspaceCanvasArea', '/projects/workspace/WorkspaceCanvasArea', Record<never, never>, Record<never, never>>,
    '/projects/workspace/WorkspaceCollaboratorsModal': RouteRecordInfo<'/projects/workspace/WorkspaceCollaboratorsModal', '/projects/workspace/WorkspaceCollaboratorsModal', Record<never, never>, Record<never, never>>,
    '/projects/workspace/WorkspaceEpisodeSidebar': RouteRecordInfo<'/projects/workspace/WorkspaceEpisodeSidebar', '/projects/workspace/WorkspaceEpisodeSidebar', Record<never, never>, Record<never, never>>,
    '/projects/workspace/WorkspaceHeader': RouteRecordInfo<'/projects/workspace/WorkspaceHeader', '/projects/workspace/WorkspaceHeader', Record<never, never>, Record<never, never>>,
    '/projects/workspace/WorkspaceRenderReviewModal': RouteRecordInfo<'/projects/workspace/WorkspaceRenderReviewModal', '/projects/workspace/WorkspaceRenderReviewModal', Record<never, never>, Record<never, never>>,
    '/settings/SettingsPage': RouteRecordInfo<'/settings/SettingsPage', '/settings/SettingsPage', Record<never, never>, Record<never, never>>,
    '/settings/tabs/ApiModelsTab': RouteRecordInfo<'/settings/tabs/ApiModelsTab', '/settings/tabs/ApiModelsTab', Record<never, never>, Record<never, never>>,
    '/settings/tabs/AssetHostingTab': RouteRecordInfo<'/settings/tabs/AssetHostingTab', '/settings/tabs/AssetHostingTab', Record<never, never>, Record<never, never>>,
    '/settings/tabs/BillingTab': RouteRecordInfo<'/settings/tabs/BillingTab', '/settings/tabs/BillingTab', Record<never, never>, Record<never, never>>,
    '/settings/tabs/LegalTab': RouteRecordInfo<'/settings/tabs/LegalTab', '/settings/tabs/LegalTab', Record<never, never>, Record<never, never>>,
    '/settings/tabs/ObservabilityTab': RouteRecordInfo<'/settings/tabs/ObservabilityTab', '/settings/tabs/ObservabilityTab', Record<never, never>, Record<never, never>>,
    '/settings/tabs/PlatformsTab': RouteRecordInfo<'/settings/tabs/PlatformsTab', '/settings/tabs/PlatformsTab', Record<never, never>, Record<never, never>>,
    '/settings/tabs/ProfileTab': RouteRecordInfo<'/settings/tabs/ProfileTab', '/settings/tabs/ProfileTab', Record<never, never>, Record<never, never>>,
    '/settings/tabs/RenderClusterTab': RouteRecordInfo<'/settings/tabs/RenderClusterTab', '/settings/tabs/RenderClusterTab', Record<never, never>, Record<never, never>>,
    '/settings/tabs/TeamTab': RouteRecordInfo<'/settings/tabs/TeamTab', '/settings/tabs/TeamTab', Record<never, never>, Record<never, never>>,
    '/settings/tabs/UserDirectoryTab': RouteRecordInfo<'/settings/tabs/UserDirectoryTab', '/settings/tabs/UserDirectoryTab', Record<never, never>, Record<never, never>>,
    '/Terms': RouteRecordInfo<'/Terms', '/Terms', Record<never, never>, Record<never, never>>,
  }
}
